### ISSUE TITLE
 The function does not work

### ISSUE THREAD

**Issue by Sang-bin** [AllTheMods/OreExcavationIntegration#4]
[00:55:57] [Server thread/ERROR] [FML]: Exception caught during firing event oreexcavation.events.EventExcavate$Pre@12edc5e7:
java.lang.NoSuchFieldError: DEFAULT
	at atm.bloodworkxgaming.oeintegration.Handler.IntegrationHandler.changeToolOverwriteEnchantment(IntegrationHandler.java:63) ~[IntegrationHandler.class:?]
	at atm.bloodworkxgaming.oeintegration.Handler.EventHandler.onExcavateEvent(EventHandler.java:24) ~[EventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_446_EventHandler_onExcavateEvent_Pre.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:632) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:588) [EventBus.class:?]
	at oreexcavation.handlers.MiningScheduler.startMining(MiningScheduler.java:80) [MiningScheduler.class:?]
	at oreexcavation.network.PacketExcavation$ServerHandler$2.run(PacketExcavation.java:123) [PacketExcavation$ServerHandler$2.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:239) [SpongeImplHooks.class:1.10.2-2477-5.2.0-BETA-2698]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zhp000(MinecraftServer.java:3745) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
[00:55:57] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[00:55:57] [Server thread/ERROR] [FML]: 0: NORMAL
[00:55:57] [Server thread/ERROR] [FML]: 1: ASM: atm.bloodworkxgaming.oeintegration.Handler.EventHandler@1b82d488 onExcavateEvent(Loreexcavation/events/EventExcavate$Pre;)V
[00:55:57] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: DEFAULT
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:239) [SpongeImplHooks.class:1.10.2-2477-5.2.0-BETA-2698]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zhp000(MinecraftServer.java:3745) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NoSuchFieldError: DEFAULT
	at atm.bloodworkxgaming.oeintegration.Handler.IntegrationHandler.changeToolOverwriteEnchantment(IntegrationHandler.java:63) ~[IntegrationHandler.class:?]
	at atm.bloodworkxgaming.oeintegration.Handler.EventHandler.onExcavateEvent(EventHandler.java:24) ~[EventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_446_EventHandler_onExcavateEvent_Pre.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:632) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:588) ~[EventBus.class:?]
	at oreexcavation.handlers.MiningScheduler.startMining(MiningScheduler.java:80) ~[MiningScheduler.class:?]
	at oreexcavation.network.PacketExcavation$ServerHandler$2.run(PacketExcavation.java:123) ~[PacketExcavation$ServerHandler$2.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 7 more

OreExcavation-1.2.107
OreExcavationIntegration-1.10.2_2.0

**Comment by BloodWorkXGaming** [comment]
Uh yeah, I know... Fixed that bug for 1.12 already, but didn't have the
time to do it for 1.10 yet...

You could downgrade ore excavation to fix it

Sang-bin <notifications@github.com> schrieb am Fr., 17. Nov. 2017, 16:57:

**Comment by BloodWorkXGaming** [comment]
Was already fixed, just forgot to close the issue ^^
